/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NewsIndexRouteImport } from './routes/news.index'
import { Route as GamesIndexRouteImport } from './routes/games.index'
import { Route as NewsSlugRouteImport } from './routes/news.$slug'
import { Route as GamesSlugRouteImport } from './routes/games.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsIndexRoute = NewsIndexRouteImport.update({
  id: '/news/',
  path: '/news/',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesIndexRoute = GamesIndexRouteImport.update({
  id: '/games/',
  path: '/games/',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsSlugRoute = NewsSlugRouteImport.update({
  id: '/news/$slug',
  path: '/news/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesSlugRoute = GamesSlugRouteImport.update({
  id: '/games/$slug',
  path: '/games/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/games/$slug': typeof GamesSlugRoute
  '/news/$slug': typeof NewsSlugRoute
  '/games/': typeof GamesIndexRoute
  '/news/': typeof NewsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/games/$slug': typeof GamesSlugRoute
  '/news/$slug': typeof NewsSlugRoute
  '/games': typeof GamesIndexRoute
  '/news': typeof NewsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/games/$slug': typeof GamesSlugRoute
  '/news/$slug': typeof NewsSlugRoute
  '/games/': typeof GamesIndexRoute
  '/news/': typeof NewsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/games/$slug' | '/news/$slug' | '/games/' | '/news/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/games/$slug' | '/news/$slug' | '/games' | '/news'
  id: '__root__' | '/' | '/games/$slug' | '/news/$slug' | '/games/' | '/news/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GamesSlugRoute: typeof GamesSlugRoute
  NewsSlugRoute: typeof NewsSlugRoute
  GamesIndexRoute: typeof GamesIndexRoute
  NewsIndexRoute: typeof NewsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/': {
      id: '/news/'
      path: '/news'
      fullPath: '/news/'
      preLoaderRoute: typeof NewsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/': {
      id: '/games/'
      path: '/games'
      fullPath: '/games/'
      preLoaderRoute: typeof GamesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/$slug': {
      id: '/news/$slug'
      path: '/news/$slug'
      fullPath: '/news/$slug'
      preLoaderRoute: typeof NewsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/$slug': {
      id: '/games/$slug'
      path: '/games/$slug'
      fullPath: '/games/$slug'
      preLoaderRoute: typeof GamesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GamesSlugRoute: GamesSlugRoute,
  NewsSlugRoute: NewsSlugRoute,
  GamesIndexRoute: GamesIndexRoute,
  NewsIndexRoute: NewsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
